name: BuildAndRelease

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout and build PowerApps pack/unpack tool
      run:  git clone https://github.com/microsoft/PowerApps-Language-Tooling.git
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Build PowerApps pack/unpack tool
      run: .\PowerApps-Language-Tooling\build.cmd
    - name: Prepare output folder
      run: mkdir buildoutput
    - name: Pack Area Inspection
      run: |
            cd "Area Inspection"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_areainspection_9036a.msapp .\DataverseSolution\CanvasApps\msft_areainspection_9036a_DocumentUri_src\
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_areainspectionmanager_a6427.msapp .\DataverseSolution\CanvasApps\msft_areainspectionmanager_a6427_DocumentUri_src\
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_reviewinspections_1dd45.msapp .\DataverseSolution\CanvasApps\msft_reviewinspections_1dd45_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_areainspection_9036a_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_areainspectionmanager_a6427_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_reviewinspections_1dd45_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "Area Inspection"
            move DataverseSolution.zip "Area Inspection"
            move TeamsCustomApp.zip "Area Inspection"
            move "Area Inspection" ..\buildoutput
            cd ..
    - name: Pack Boards
      run: |
            cd "Boards"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_boards_d2409.msapp .\DataverseSolution\CanvasApps\msft_boards_d2409_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_boards_d2409_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "Boards"
            move DataverseSolution.zip "Boards"
            move TeamsCustomApp.zip "Boards"
            move "Boards" ..\buildoutput
            cd ..
    - name: Pack Bulletins
      run: |
            cd "Bulletins"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_bulletins_15705.msapp .\DataverseSolution\CanvasApps\msft_bulletins_15705_DocumentUri_src\
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_managebulletins_c25aa.msapp .\DataverseSolution\CanvasApps\msft_managebulletins_c25aa_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_bulletins_15705_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_managebulletins_c25aa_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "Bulletins"
            move DataverseSolution.zip "Bulletins"
            move TeamsCustomApp.zip "Bulletins"
            move "Bulletins" ..\buildoutput
            cd ..
    - name: Pack Employee Ideas
      run: |
            cd "Employee Ideas"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_employeeideas_955d7.msapp .\DataverseSolution\CanvasApps\msft_employeeideas_955d7_DocumentUri_src\
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_employeeideasmanager_f172c.msapp .\DataverseSolution\CanvasApps\msft_employeeideasmanager_f172c_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_employeeideas_955d7_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_employeeideasmanager_f172c_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "Employee Ideas"
            move DataverseSolution.zip "Employee Ideas"
            move TeamsCustomApp.zip "Employee Ideas"
            move "Employee Ideas" ..\buildoutput
            cd ..
    - name: Pack HowTo
      run: |
            cd "HowTo"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_howto_8999a.msapp .\DataverseSolution\CanvasApps\msft_howto_8999a_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_howto_8999a_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "HowTo"
            move DataverseSolution.zip "HowTo"
            move TeamsCustomApp.zip "HowTo"
            move "HowTo" ..\buildoutput
            cd ..
    - name: Pack IssueReporting
      run: |
            cd "IssueReporting"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_issuereporting_b51d5.msapp .\DataverseSolution\CanvasApps\msft_issuereporting_b51d5_DocumentUri_src\
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_manageissues_14672.msapp .\DataverseSolution\CanvasApps\msft_manageissues_14672_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_issuereporting_b51d5_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_manageissues_14672_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "IssueReporting"
            move DataverseSolution.zip "IssueReporting"
            move TeamsCustomApp.zip "IssueReporting"
            move "IssueReporting" ..\buildoutput
            cd ..
    - name: Pack GetConnected
      run: |
            cd "GetConnected"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_getconnected_c1367.msapp .\DataverseSolution\CanvasApps\msft_getconnected_c1367_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_getconnected_c1367_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "GetConnected"
            move DataverseSolution.zip "GetConnected"
            move TeamsCustomApp.zip "GetConnected"
            move "GetConnected" ..\buildoutput
            cd ..
    - name: Pack Milestones
      run: |
            cd Milestones
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_milestones_5daaa.msapp .\DataverseSolution\CanvasApps\msft_milestones_5daaa_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_milestones_5daaa_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir Milestones
            move DataverseSolution.zip Milestones
            move TeamsCustomApp.zip Milestones
            powershell Move-Item -Path Milestones -Destination ..\buildoutput
            cd ..
    - name: Pack Perspectives
      run: |
            cd "Perspectives"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_perspectives_a1249.msapp .\DataverseSolution\CanvasApps\msft_perspectives_a1249_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_perspectives_a1249_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "Perspectives"
            move DataverseSolution.zip "Perspectives"
            move TeamsCustomApp.zip "Perspectives"
            move "Perspectives" ..\buildoutput
            cd ..
    - name: Pack ProfilePlus
      run: |
            cd "ProfilePlus"
            ..\PowerApps-Language-Tooling\bin\Debug\PASopa\PASopa.exe -pack .\DataverseSolution\CanvasApps\msft_profile_20ce1.msapp .\DataverseSolution\CanvasApps\msft_profile_20ce1_DocumentUri_src\
            powershell rm -r DataverseSolution\CanvasApps\msft_profile_20ce1_DocumentUri_src\
            powershell Compress-Archive DataverseSolution\* DataverseSolution.zip
            powershell Compress-Archive TeamsCustomApp\* TeamsCustomApp.zip
            mkdir "ProfilePlus"
            move DataverseSolution.zip "ProfilePlus"
            move TeamsCustomApp.zip "ProfilePlus"
            move "ProfilePlus" ..\buildoutput
            cd ..
    - name: Pack outputs
      run: |
            powershell Compress-Archive buildoutput\* AppPackages.zip
            dir
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.RUN_NUMBER }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: AppPackages.zip
        asset_name: AppPackages.zip
        asset_content_type: application/zip
